package com.mygdx.game;

import com.badlogic.gdx.physics.box2d.Body;
import com.badlogic.gdx.physics.box2d.Fixture;
import com.badlogic.gdx.physics.box2d.FixtureDef;

/**
 *
 * @author alexh
 */
public class Fighter {

    /** Array of all Fighters. */
    public static final Fighter[] FIGHTERS = new Fighter[] {
        new Fighter("Fighter1", 10, 1, 5),
    };

    /** Name of the Character. */
    private final String m_name;

    /** The amount of force to apply to the Y Axis. */
    private final float m_jumpForce;

    /** Weight, effects Launch percent. Damage Calcs */
    private final float m_weight;

    /** Amount of Pixels to Move per Frame */
    private final float m_runSpeed;

    /** Current health in Percent. */
    private float m_health;

    /** Body of the Fighter generated by the World. */
    private Body m_body;

    /** Fixture of the Fighter generated by the Body. */
    private Fixture m_fixture;


    /**
     * Constructor for the Fighter Class.
     * @param name 
     * @param runSpeed
     * @param jumpForce
     * @param weight
     */
    public Fighter(String name, float runSpeed, float jumpForce, float weight) {
        m_name = name;
        m_jumpForce = jumpForce;
        m_weight = weight;
        m_runSpeed = runSpeed;
    }

    public String getName() {
        return m_name;
    }
    
    public float getHealth() {
        return m_health;
    }

    public void setHealth(float health) {
        m_health = health;
    }

    public float getJumpForce() {
        return m_jumpForce;
    }

    public float getWeight() {
        return m_weight;
    }

    public float getRunSpeed() {
        return m_runSpeed;
    }

    public void setBody(Body body) {
        m_body = body;
    }

    public Body getBody() {
        return m_body;
    }

    public Fixture getFixture() {
        return m_fixture;
    }

    public void generateFixture(FixtureDef fixtureDef) {
        m_fixture = m_body.createFixture(fixtureDef);
    }
   
}
